// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kibxjqfyavjniiqicddd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpYnhqcWZ5YXZqbmlpcWljZGRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyODA4MDksImV4cCI6MjA1Njg1NjgwOX0.Vfng4POpH7HzXsisl-BzYuX23MyDRWjTc0leKNrsL7Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);